# Generated by Django 4.0.5 on 2023-09-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0002_referral'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Referral',
        ),
    ]
