# Generated by Django 5.0.1 on 2024-02-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0003_delete_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='goal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
