# Generated by Django 5.0.1 on 2024-02-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0004_user_goal_user_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('returns', models.IntegerField(default=0)),
            ],
        ),
    ]
