# Generated by Django 4.0.5 on 2024-02-02 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0005_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='family_no_dep',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='has_child',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_loan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='loan_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='loan_emi',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='num_children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_age', models.IntegerField(null=True)),
                ('child_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('child_edu_expi', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
