# Generated by Django 4.0.5 on 2024-03-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0009_fdpartner_interestrate_interestratedetail_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='conclusion',
        ),
    ]
