# Generated by Django 4.0.5 on 2024-03-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0010_remove_faq_conclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdpartner',
            name='lastRevisedDate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fdpartner',
            name='lastRevisedDateAbove2Cr',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
