# Generated by Django 4.0.5 on 2024-03-07 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0011_alter_fdpartner_lastreviseddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fdpartner',
            old_name='lastRevisedDate',
            new_name='lastRevised',
        ),
        migrations.RenameField(
            model_name='fdpartner',
            old_name='lastRevisedDateAbove2Cr',
            new_name='lastRevisedAbove2Cr',
        ),
    ]
