# Generated by Django 4.0.5 on 2024-03-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0012_rename_lastreviseddate_fdpartner_lastrevised_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fdpartner',
            old_name='lastRevised',
            new_name='lastRevisedDate',
        ),
        migrations.RenameField(
            model_name='fdpartner',
            old_name='lastRevisedAbove2Cr',
            new_name='lastRevisedDateAbove2Cr',
        ),
    ]
