# Generated by Django 4.0.5 on 2024-03-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0013_rename_lastrevised_fdpartner_lastreviseddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='bulletPoints',
            field=models.TextField(null=True),
        ),
    ]
