# Generated by Django 4.0.5 on 2024-03-07 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0015_alter_interestrate_fd_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestratedetail',
            name='interest_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interestRatesList', to='testapp1.interestrate'),
        ),
    ]
