# Generated by Django 4.0.5 on 2024-03-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0016_alter_interestratedetail_interest_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fdpartner',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
