# Generated by Django 4.0.5 on 2024-03-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0017_alter_fdpartner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HOST_USER', models.CharField(max_length=555)),
                ('HOST_PASSWORD', models.CharField(max_length=555)),
            ],
        ),
    ]
