# Generated by Django 4.0.5 on 2024-03-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0018_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='HOST_KEY',
            field=models.CharField(max_length=555, null=True),
        ),
    ]
