# Generated by Django 4.0.5 on 2024-03-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0019_password_host_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='HOST_KEY',
            field=models.BinaryField(max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='password',
            name='HOST_PASSWORD',
            field=models.BinaryField(max_length=555),
        ),
        migrations.AlterField(
            model_name='password',
            name='HOST_USER',
            field=models.BinaryField(max_length=555),
        ),
    ]
