# Generated by Django 4.0.5 on 2024-04-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp1', '0022_user_goaldura_user_has_insurance_user_insurance_emi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='goal',
            new_name='goalAmount',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='goaldura',
            new_name='goalDuration',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='has_insurance',
            new_name='hasInsurance',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='has_loan',
            new_name='hasLoan',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='insurance_emi',
            new_name='insuranceAmount',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='loan_duration',
            new_name='laondura',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='loan_emi',
            new_name='loanAmount',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='monthly_expi',
            new_name='monthlyExpenditure',
        ),
    ]
